### PR TITLE
Adding l10n files for localization 'de' as EXT:templavoilaplus is not on translations.typo3.org

### PR DESCRIPTION
**Pull request by jpmschuler**
Took the l10n files from old templavoila and added them, at least the basic files needed and added de.BackendLayout.xlf (based on mod1/locallang.xlf) under the assumption that for administrators English is enough, but editors would need a l10n version.

Also, minor CSS change for unblurrring icons (sorry, didn't know how to cherry pick only l10n files this correctly)

### CODE REVIEW

**Comment by opi99** [comment]
Hi, thanks for your pull request.
Yes right, we are not on translation server, for this we need a regular user base of 120 users. I spoke with Xavier, as there are also other ways to provide such files.
But ATM my web server is not up to date, to provide l10n files yet, but hopefully this will change.
So, yet, I wouldn't add this files to the extension, maybe later if this do not work with my server.

**Comment by opi99** [comment]
The css thing ... ohh yes ... but it looks like the complete definition of .tpm-bottom-control img{} can be removed.

**Comment by jpmschuler** [comment]
@l10n Well yes, I am aware of that restriction. That's why the option to supply languages in the extension is possible. Installing an own l10n server would be an unnecessary overload IMHO.
Well then I will use a https://docs.typo3.org/typo3cms/extensions/autoloader/Loader/LanguageOverride.html meanwhile to put the files locally (and mention this here in case someone doesn't know of this option).

@css  I made a 7LTS compatible tv mod1 months ago and made many css fixes in the process to make the look and feel like the rest of the new backend theme, just can't handle all the small bugs and the missing mod2 of my version anymore. So I thought before throwing everything away I could step by step cherry pick everything of value into tv+ in the process of migrating to it.

**Comment by opi99** [comment]
@l10n implemented now with #59 and uploaded a de zip file with the BackandLayout.xlf in German *hurra* :-) So using latest git should work with translation update.

@css Never found your branch ... I started of from the work which Benni already did after the (more or less unusable) 2.0.4 releases.

**Comment by opi99** [comment]
Hi, thx for all that help. I would take over some of the selected changes, but there are some points which should be changed:

- As in TYPO3 core, I like to have styled commit messages, so we are in need of creating issues. See https://wiki.typo3.org/CommitMessage_Format_%28Git%29 and take a look into last commits.
- Only one issue per merge request, so I can review issue for issue.
- Do not change indentation or styling of the source. If it is needed, as it do not comply to the guidelines, then this shouldn't be mixed with code changes. Else it is hard to find the real change in source.

I hope you are still willing to help, if something is unclear we may chat on slack together.
Greetings Alex//

**Comment by jpmschuler** [comment]
sry didn't think that local changes to my branches would be added to this pull request afterwards, thought that the pull request is "commit frozen". Will act accordingly.

**Comment by opi99** [comment]
Hmmm, this seams a pull request over a complete branch and not over selected commits.

**Comment by jpmschuler** [comment]
closing pull request for cleanup

**Pull request closed without merging**
