### PR TITLE
[FEATURE] Adapt design of page module to 7LTS new backend styles

### PR DESCRIPTION
**Pull request by jpmschuler**
Idea is to harmonise the design between the modules. Copying design from
TYPO3 core page module a bit and adapting colouring and spacing.
Especially removing floats and font-size declarations from old
6LTS-templavoila-CSS file.

Resolves: #60

### CODE REVIEW

**Comment by opi99** [comment]
After applying your patch the alignment isn't middle anymore. Is this something on my test system?

screenshot_20170512_115358

**Comment by opi99** [comment]
For me it looks perfectly if i change following

`.tpm-element-title .tpm-langIcon, .tpm-element-title .tpm-buttonsLeft {
    padding-right: 0.5em;
    vertical-align: top;
}
.t3-row-header .tpm-element-title {
    line-height: 15px;
    vertical-align: top;
}`

Using the console inside firefox.

**Comment by jpmschuler** [comment]
Changed the commit. Your idea didn't solve the problem as it was fixed in FF, but broken in Safari afterwards. 
The line-height was calculated twice in FF, so the dark box was larger than it was defined. I revamped some code so it looks fine in Safari, Firefox and Edge to me.

The alignment is "top right", just a bit off. I changed the whole floating and top-align stuff because this breaks on rather small columns/displays.

I found some more differences in the progress between the browsers, like referenced elements' header being styled completely different.

**Comment by opi99** [comment]
If it helps I can also change the HTML elements, adding/removing classes/ids and so on. :-)

**Comment by jpmschuler** [comment]
Wonderful!

I think there are enough classes in the code already to pinpoint every element, so IMHO no need.

**Pull request merged**
